version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ec2-user/server
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: deploy/validate_service.sh
      timeout: 300
      runas: root